export interface BibleBook {
  id: string;
  nameEn: string;
  nameAm: string;
  chapters: number;
  testament: 'OT' | 'NT' | 'deutero';
}

export const EOTC_BIBLE_BOOKS: BibleBook[] = [
  { id: 'gen', nameEn: 'Genesis', nameAm: 'ዘፍጥረት', chapters: 50, testament: 'OT' },
  { id: 'exod', nameEn: 'Exodus', nameAm: 'ዘፀአት', chapters: 40, testament: 'OT' },
  { id: 'lev', nameEn: 'Leviticus', nameAm: 'ዘሌዋውያን', chapters: 27, testament: 'OT' },
  { id: 'num', nameEn: 'Numbers', nameAm: 'ዘቁጥር', chapters: 36, testament: 'OT' },
  { id: 'deut', nameEn: 'Deuteronomy', nameAm: 'ዘዳግም', chapters: 34, testament: 'OT' },
  { id: 'josh', nameEn: 'Joshua', nameAm: 'ኢያሱ', chapters: 24, testament: 'OT' },
  { id: 'judg', nameEn: 'Judges', nameAm: 'መሳፍንት', chapters: 21, testament: 'OT' },
  { id: 'ruth', nameEn: 'Ruth', nameAm: 'ሩት', chapters: 4, testament: 'OT' },
  { id: '1sam', nameEn: '1 Samuel', nameAm: '1 ሳሙኤል', chapters: 31, testament: 'OT' },
  { id: '2sam', nameEn: '2 Samuel', nameAm: '2 ሳሙኤል', chapters: 24, testament: 'OT' },
  { id: '1kgs', nameEn: '1 Kings', nameAm: '1 ነገሥት', chapters: 22, testament: 'OT' },
  { id: '2kgs', nameEn: '2 Kings', nameAm: '2 ነገሥት', chapters: 25, testament: 'OT' },
  { id: '1chr', nameEn: '1 Chronicles', nameAm: '1 ዜና መዋዕል', chapters: 29, testament: 'OT' },
  { id: '2chr', nameEn: '2 Chronicles', nameAm: '2 ዜና መዋዕል', chapters: 36, testament: 'OT' },
  { id: 'ezra', nameEn: 'Ezra', nameAm: 'ዕዝራ', chapters: 10, testament: 'OT' },
  { id: 'neh', nameEn: 'Nehemiah', nameAm: 'ነህምያ', chapters: 13, testament: 'OT' },
  { id: 'esth', nameEn: 'Esther', nameAm: 'አስቴር', chapters: 10, testament: 'OT' },
  { id: 'job', nameEn: 'Job', nameAm: 'ኢዮብ', chapters: 42, testament: 'OT' },
  { id: 'ps', nameEn: 'Psalms', nameAm: 'መዝሙረ ዳዊት', chapters: 151, testament: 'OT' },
  { id: 'prov', nameEn: 'Proverbs', nameAm: 'ምሳሌ', chapters: 31, testament: 'OT' },
  { id: 'eccl', nameEn: 'Ecclesiastes', nameAm: 'መክብብ', chapters: 12, testament: 'OT' },
  { id: 'song', nameEn: 'Song of Songs', nameAm: 'መኃልየ ሰሎሞን', chapters: 8, testament: 'OT' },
  { id: 'isa', nameEn: 'Isaiah', nameAm: 'ኢሳይያስ', chapters: 66, testament: 'OT' },
  { id: 'jer', nameEn: 'Jeremiah', nameAm: 'ኤርምያስ', chapters: 52, testament: 'OT' },
  { id: 'lam', nameEn: 'Lamentations', nameAm: 'ሰቆቃወ ኤርምያስ', chapters: 5, testament: 'OT' },
  { id: 'ezek', nameEn: 'Ezekiel', nameAm: 'ሕዝቅኤል', chapters: 48, testament: 'OT' },
  { id: 'dan', nameEn: 'Daniel', nameAm: 'ዳንኤል', chapters: 12, testament: 'OT' },
  { id: 'hos', nameEn: 'Hosea', nameAm: 'ሆሴዕ', chapters: 14, testament: 'OT' },
  { id: 'joel', nameEn: 'Joel', nameAm: 'ኢዮኤል', chapters: 3, testament: 'OT' },
  { id: 'amos', nameEn: 'Amos', nameAm: 'አሞጽ', chapters: 9, testament: 'OT' },
  { id: 'obad', nameEn: 'Obadiah', nameAm: 'አብድዩ', chapters: 1, testament: 'OT' },
  { id: 'jonah', nameEn: 'Jonah', nameAm: 'ዮናስ', chapters: 4, testament: 'OT' },
  { id: 'mic', nameEn: 'Micah', nameAm: 'ሚክያስ', chapters: 7, testament: 'OT' },
  { id: 'nah', nameEn: 'Nahum', nameAm: 'ናሆም', chapters: 3, testament: 'OT' },
  { id: 'hab', nameEn: 'Habakkuk', nameAm: 'ዕንባቆም', chapters: 3, testament: 'OT' },
  { id: 'zeph', nameEn: 'Zephaniah', nameAm: 'ሶፎንያስ', chapters: 3, testament: 'OT' },
  { id: 'hag', nameEn: 'Haggai', nameAm: 'ሐጌ', chapters: 2, testament: 'OT' },
  { id: 'zech', nameEn: 'Zechariah', nameAm: 'ዘካርያስ', chapters: 14, testament: 'OT' },
  { id: 'mal', nameEn: 'Malachi', nameAm: 'ሚልክያስ', chapters: 4, testament: 'OT' },
  { id: 'tob', nameEn: 'Tobit', nameAm: 'ጦቢት', chapters: 14, testament: 'deutero' },
  { id: 'jdt', nameEn: 'Judith', nameAm: 'ዩዲት', chapters: 16, testament: 'deutero' },
  { id: '1macc', nameEn: '1 Maccabees', nameAm: '1 መቃብያን', chapters: 16, testament: 'deutero' },
  { id: '2macc', nameEn: '2 Maccabees', nameAm: '2 መቃብያን', chapters: 15, testament: 'deutero' },
  { id: '3macc', nameEn: '3 Maccabees', nameAm: '3 መቃብያን', chapters: 7, testament: 'deutero' },
  { id: 'sir', nameEn: 'Sirach', nameAm: 'ሲራክ', chapters: 51, testament: 'deutero' },
  { id: 'wis', nameEn: 'Wisdom of Solomon', nameAm: 'ጥበበ ሰሎሞን', chapters: 19, testament: 'deutero' },
  { id: 'matt', nameEn: 'Matthew', nameAm: 'ማቴዎስ', chapters: 28, testament: 'NT' },
  { id: 'mark', nameEn: 'Mark', nameAm: 'ማርቆስ', chapters: 16, testament: 'NT' },
  { id: 'luke', nameEn: 'Luke', nameAm: 'ሉቃስ', chapters: 24, testament: 'NT' },
  { id: 'john', nameEn: 'John', nameAm: 'ዮሐንስ', chapters: 21, testament: 'NT' },
  { id: 'acts', nameEn: 'Acts', nameAm: 'የሐዋርያት ሥራ', chapters: 28, testament: 'NT' },
  { id: 'rom', nameEn: 'Romans', nameAm: 'ሮሜ', chapters: 16, testament: 'NT' },
  { id: '1cor', nameEn: '1 Corinthians', nameAm: '1 ቆሮንቶስ', chapters: 16, testament: 'NT' },
  { id: '2cor', nameEn: '2 Corinthians', nameAm: '2 ቆሮንቶስ', chapters: 13, testament: 'NT' },
  { id: 'gal', nameEn: 'Galatians', nameAm: 'ገላትያ', chapters: 6, testament: 'NT' },
  { id: 'eph', nameEn: 'Ephesians', nameAm: 'ኤፌሶን', chapters: 6, testament: 'NT' },
  { id: 'phil', nameEn: 'Philippians', nameAm: 'ፊልጵስዩስ', chapters: 4, testament: 'NT' },
  { id: 'col', nameEn: 'Colossians', nameAm: 'ቆላስያስ', chapters: 4, testament: 'NT' },
  { id: '1thess', nameEn: '1 Thessalonians', nameAm: '1 ተሰሎንቄ', chapters: 5, testament: 'NT' },
  { id: '2thess', nameEn: '2 Thessalonians', nameAm: '2 ተሰሎንቄ', chapters: 3, testament: 'NT' },
  { id: '1tim', nameEn: '1 Timothy', nameAm: '1 ጢሞቴዎስ', chapters: 6, testament: 'NT' },
  { id: '2tim', nameEn: '2 Timothy', nameAm: '2 ጢሞቴዎስ', chapters: 4, testament: 'NT' },
  { id: 'tit', nameEn: 'Titus', nameAm: 'ቲቶ', chapters: 3, testament: 'NT' },
  { id: 'phlm', nameEn: 'Philemon', nameAm: 'ፊልሞና', chapters: 1, testament: 'NT' },
  { id: 'heb', nameEn: 'Hebrews', nameAm: 'ዕብራውያን', chapters: 13, testament: 'NT' },
  { id: 'jas', nameEn: 'James', nameAm: 'ያዕቆብ', chapters: 5, testament: 'NT' },
  { id: '1pet', nameEn: '1 Peter', nameAm: '1 ጴጥሮስ', chapters: 5, testament: 'NT' },
  { id: '2pet', nameEn: '2 Peter', nameAm: '2 ጴጥሮስ', chapters: 3, testament: 'NT' },
  { id: '1john', nameEn: '1 John', nameAm: '1 ዮሐንስ', chapters: 5, testament: 'NT' },
  { id: '2john', nameEn: '2 John', nameAm: '2 ዮሐንስ', chapters: 1, testament: 'NT' },
  { id: '3john', nameEn: '3 John', nameAm: '3 ዮሐንስ', chapters: 1, testament: 'NT' },
  { id: 'jude', nameEn: 'Jude', nameAm: 'ይሁዳ', chapters: 1, testament: 'NT' },
  { id: 'rev', nameEn: 'Revelation', nameAm: 'ራዕይ', chapters: 22, testament: 'NT' },
  { id: 'enoch', nameEn: '1 Enoch', nameAm: 'ሄኖክ', chapters: 108, testament: 'deutero' },
  { id: 'jub', nameEn: 'Jubilees', nameAm: 'ኩፋሌ', chapters: 50, testament: 'deutero' },
  { id: 'shen', nameEn: '4 Ezra (Ezra Sutuel)', nameAm: 'ዕዝራ ሱቱኤል', chapters: 16, testament: 'deutero' },
  { id: 'rep', nameEn: 'Shepherd of Hermas', nameAm: 'ሄርማስ', chapters: 5, testament: 'deutero' },
  { id: 'did', nameEn: 'Didascalia', nameAm: 'ዲድስቃልያ', chapters: 26, testament: 'deutero' },
];

export function formatBibleRef(bookId: string, chapter: number, language: 'am' | 'en'): string {
  const book = EOTC_BIBLE_BOOKS.find(b => b.id === bookId);
  if (!book) return '';
  return `${language === 'am' ? book.nameAm : book.nameEn} ${chapter}`;
}
